[package]
name = "eza"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(target_os = "windows")'.dependencies]
windows = "0.38.0"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24.0"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.15.5"
